-- =============================================================================
-- HE THONG CO SO DU LIEU QUAN LY DON DAT HANG & PHIEU GIAO HANG
-- Mo hinh duoc chuan hoa theo 3NF (Third Normal Form)
-- =============================================================================

-- 1. BANG THUC THE MASTER / DANH MUC
-- Bang Don vi khach (Gop Don vi dat hang & Don vi khach hang)
CREATE TABLE DON_VI_KHACH (
    MaDV VARCHAR(20) NOT NULL PRIMARY KEY,
    TenDV NVARCHAR(100) NOT NULL,
    DiaChi NVARCHAR(200),
    DienThoai VARCHAR(20)
);

-- Bang Nguoi dat hang (Thuoc Don vi khach)
CREATE TABLE NGUOI_DAT (
    MaND VARCHAR(20) NOT NULL PRIMARY KEY,
    HoTenND NVARCHAR(100) NOT NULL,
    MaDV VARCHAR(20) NOT NULL,
    CONSTRAINT FK_NguoiDat_DonViKhach FOREIGN KEY (MaDV) 
        REFERENCES DON_VI_KHACH(MaDV) ON UPDATE CASCADE ON DELETE RESTRICT
);

-- Bang Nguoi nhan hang (Thuoc Don vi khach)
CREATE TABLE NGUOI_NHAN (
    MaNN VARCHAR(20) NOT NULL PRIMARY KEY,
    HoTenNN NVARCHAR(100) NOT NULL,
    MaDV VARCHAR(20) NOT NULL,
    CONSTRAINT FK_NguoiNhan_DonViKhach FOREIGN KEY (MaDV) 
        REFERENCES DON_VI_KHACH(MaDV) ON UPDATE CASCADE ON DELETE RESTRICT
);

-- Bang Nguoi giao hang (Nhan vien giao cua cua hang)
CREATE TABLE NGUOI_GIAO (
    MaNG VARCHAR(20) NOT NULL PRIMARY KEY,
    HoTenNG NVARCHAR(100) NOT NULL
);

-- Bang Dia diem / Noi giao hang
CREATE TABLE NOI_GIAO (
    MaDDG VARCHAR(20) NOT NULL PRIMARY KEY,
    TenNoiGiao NVARCHAR(200) NOT NULL
);

-- Bang Danh muc Hang hoa
CREATE TABLE HANG_HOA (
    MaHang VARCHAR(20) NOT NULL PRIMARY KEY,
    TenHang NVARCHAR(100) NOT NULL,
    DvTinh NVARCHAR(50) NOT NULL,
    MoTaHang NVARCHAR(MAX)
);

-- 2. BANG NGHIEP VU GIAO DICH (TRANSACTION TABLES)
-- Bang Don dat hang (Master)
CREATE TABLE DON_DAT_HANG (
    SoDH VARCHAR(20) NOT NULL PRIMARY KEY,
    NgayDat DATE NOT NULL,
    MaND VARCHAR(20) NOT NULL,
    CONSTRAINT FK_DonDatHang_NguoiDat FOREIGN KEY (MaND) 
        REFERENCES NGUOI_DAT(MaND) ON UPDATE CASCADE ON DELETE RESTRICT
);

-- Bang Chi tiet Don dat hang (Detail)
CREATE TABLE CHI_TIET_DAT_HANG (
    SoDH VARCHAR(20) NOT NULL,
    MaHang VARCHAR(20) NOT NULL,
    SoLuongDat INT NOT NULL CHECK (SoLuongDat > 0),
    PRIMARY KEY (SoDH, MaHang),
    CONSTRAINT FK_CTDH_DonDatHang FOREIGN KEY (SoDH) 
        REFERENCES DON_DAT_HANG(SoDH) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_CTDH_HangHoa FOREIGN KEY (MaHang) 
        REFERENCES HANG_HOA(MaHang) ON UPDATE CASCADE ON DELETE RESTRICT
);

-- Bang Phieu giao hang (Master)
CREATE TABLE PHIEU_GIAO_HANG (
    SoPG VARCHAR(20) NOT NULL PRIMARY KEY,
    NgayGiao DATE NOT NULL,
    SoDH VARCHAR(20) NOT NULL,
    MaNG VARCHAR(20) NOT NULL,
    MaNN VARCHAR(20) NOT NULL,
    MaDDG VARCHAR(20) NOT NULL,
    CONSTRAINT FK_PhieuGiao_DonDatHang FOREIGN KEY (SoDH) 
        REFERENCES DON_DAT_HANG(SoDH) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT FK_PhieuGiao_NguoiGiao FOREIGN KEY (MaNG) 
        REFERENCES NGUOI_GIAO(MaNG) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT FK_PhieuGiao_NguoiNhan FOREIGN KEY (MaNN) 
        REFERENCES NGUOI_NHAN(MaNN) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT FK_PhieuGiao_NoiGiao FOREIGN KEY (MaDDG) 
        REFERENCES NOI_GIAO(MaDDG) ON UPDATE CASCADE ON DELETE RESTRICT
);

-- Bang Chi tiet Phieu giao hang (Detail)
CREATE TABLE CHI_TIET_GIAO_HANG (
    SoPG VARCHAR(20) NOT NULL,
    MaHang VARCHAR(20) NOT NULL,
    SoLuongGiao INT NOT NULL CHECK (SoLuongGiao > 0),
    DonGiaGiao DECIMAL(18, 2) NOT NULL CHECK (DonGiaGiao >= 0),
    ThanhTien DECIMAL(18, 2) NOT NULL,
    PRIMARY KEY (SoPG, MaHang),
    CONSTRAINT FK_CTGH_PhieuGiao FOREIGN KEY (SoPG) 
        REFERENCES PHIEU_GIAO_HANG(SoPG) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_CTGH_HangHoa FOREIGN KEY (MaHang) 
        REFERENCES HANG_HOA(MaHang) ON UPDATE CASCADE ON DELETE RESTRICT
);
